#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Delete the sample FabCar IBP network
  hosts: localhost

  vars_files:
    - ibmcloud-credentials.yml
    - fabcar-network-vars.yml

  roles:
    - role: ibm.blockchain_platform.ordering_organization
      vars:
        state: absent
        organization_name: "{{ ordering_org_name }}"
        organization_msp_id: "{{ ordering_org_msp_id }}"

    - role: ibm.blockchain_platform.endorsing_organization
      vars:
        state: absent
        organization_name: "{{ sample_org_name }}"
        organization_msp_id: "{{ sample_org_msp_id }}"
        peer_name: "{{ sample_org_peer_name }}"

  tasks:
    - name: Remove imported ordering service
      ibm.blockchain_platform.external_ordering_service:
        api_endpoint: "{{ api_endpoint }}"
        api_authtype: "{{ api_authtype }}"
        api_key: "{{ api_key }}"
        state: absent
        name: "{{ ordering_service_name }}"
      when: import_export_used | default(false)
